---
title: "Your Department Name"
author: "Your Name"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
---

```{r setup, include=FALSE}
library(ggplot2)
library(plotly)
library(plyr)
library(flexdashboard)

# create some data
set.seed(955)
dat <- data.frame(cond = rep(c("A", "B"), each=10),
                  xvar = 1:20 + rnorm(20,sd=3),
                  yvar = 1:20 + rnorm(20,sd=3))
```

PAGE 1
=======================================================================

Row
-----------------------------------------------------------------------

### Chart (1)

```{r}

```


### Chart (2)

```{r}

```

Row
-----------------------------------------------------------------------

### Chart (3)

```{r}

```

### Chart (4)

```{r}
hist(dat$xvar)
```

PAGE 2
=======================================================================

Row
-----------------------------------------------------------------------

### Chart (5)

```{r}

```

### Chart (6)

```{r}

```

Row
-----------------------------------------------------------------------

### Chart (7)

```{r}

```

### Chart (8)

```{r}

```
